# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true

# edit here to achieve your personal greatness
url: http://username.github.io/
baseurl: /sustain
title: Chris Turner
author: Chris Turner
description: Personal blog and resume
avatar: profile.png
email: yourname@email.com
twitter_username: username
#Comment out if you don't want disqus
disqus_username: username
google_analytics: UA-69391421-1
social:
  - url: http://github.com/jekyllt
    icon: github
  - url: mailto:yourname@email.com
    icon: envelope
  - url: https://twitter.com/username
    icon: twitter
  - url: http://linkedin.com/in/username
    icon: linkedin
  - url: http://stackoverflow.com/username
    icon: stack-overflow
  - url: https://medium.com/@username
    icon: medium

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md


# needed for travis-ci build
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
